# Anomaly Calculator configuration file

[colors]

colorscheme= "everforest-dark"

[colors.gruvbox-dark]
name = "Gruvbox Dark"
background-color = "#282828"
foreground-color = "#ebdbb2"
accent-color = "#d65d0e"

[colors.gruvbox-light]
name = "Gruvbox Light"
background-color = "#fbf1c7"
foreground-color = "#3c3836"
accent-color = "#d65d0e"

[colors.papercolor-dark]
name = "Papercolor Dark"
background-color = "#1c1c1c"
foreground-color = "#eeeeee"
accent-color = "#af005f"

[colors.papercolor-light]
name = "Papercolor Light"
background-color = "#eeeeee"
foreground-color = "#1c1c1c"
accent-color = "#af0000"

[colors.everforest-dark]
name = "Everforest Dark"
background-color = "#1e2326"
foreground-color = "#d3c6aa"
accent-color = "#e67e80"

[colors.everforest-light]
name = "Everforest Light"
background-color = "#f2efdf"
foreground-color = "#5c6a72"
accent-color = "#f85552"

[mode]
angle = "radians"

# A list of configurable keyboard shorctus

[[shortcut]]
shortcut = '0'
num = '0'

[[shortcut]]
shortcut = '1'
num = '1'

[[shortcut]]
shortcut = '2'
num = '2'

[[shortcut]]
shortcut = '3'
num = '3'

[[shortcut]]
shortcut = '4'
num = '4'

[[shortcut]]
shortcut = '5'
num = '5'

[[shortcut]]
shortcut = '6'
num = '6'

[[shortcut]]
shortcut = '7'
num = '7'

[[shortcut]]
shortcut = '8'
num = '8'

[[shortcut]]
shortcut = '9'
num = '9'

[[shortcut]]
shortcut = '+'
num = '+'

[[shortcut]]
shortcut = '-'
num = '-'

[[shortcut]]
shortcut = '*'
num = '*'

[[shortcut]]
shortcut = '/'
num = '/'

[[shortcut]]
shortcut = 'n'
num = 'plusminus'

[[shortcut]]
shortcut = 's'
num = 'sin'

[[shortcut]]
shortcut = 'c'
num = 'cos'

[[shortcut]]
shortcut = 't'
num = 'tan'

[[shortcut]]
shortcut = 'ctrl+s'
num = 'swap'

[[shortcut]]
shortcut = '^'
num = '^'

[[shortcut]]
shortcut = 'l'
num = 'ln'

[[shortcut]]
shortcut = 'return'
num = 'enter'

[[shortcut]]
shortcut = 'backspace'
num = 'backspace'

[[shortcut]]
shortcut = 'escape'
num = 'clear'

[[shortcut]]
shortcut = '.'
num = '.'

[[shortcut]]
shortcut = 'p'
num = 'pi'

[[shortcut]]
shortcut = 'shift+s'
num = 'arcsin'

[[shortcut]]
shortcut = 'shift+c'
num = 'arccos'

[[shortcut]]
shortcut = 'shift+t'
num = 'arctan'
